server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rentalcarbooking
        username: root
        password: Root@123
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        ddl-auto: update
        show-sql: true


cloudinary:
    cloud_name: Root
    api_key: 677936141658314
    api_secret: 2M7QLlAJIFmkJ6YUBvfzByDTkrU
